### ISSUE TITLE
thread 'main' panicked at 'Please set the path to the Android NDK with the $NDK_HOME environment variable.: NotPresent', src\libcore\result.rs:999:5

### ISSUE THREAD

**Issue by JordiOfRivia** [OptimisticPeach/android_rs_base#1]
Hello,
I 'm following the guide for android_base.
When i run the command  cargo-apk run
I get the following error message: "thread 'main' panicked at 'Please set the path to the Android NDK with the $NDK_HOME environment variable.: NotPresent', src\libcore\result.rs:999:5"

But i already set my path in my environment variable Like this: C:\Users\Jordi\AppData\Local\Android\android-ndk-r19b

Can somebody help me with my problem?

-Jordi

**Comment by OptimisticPeach** [comment]
Hmm, are you sure that you have followed the [cargo-apk](https://github.com/tomaka/android-rs-glue#setting-up-your-environment) setup properly? Note at the end where it says 
> - Set the environment variables NDK_HOME to the path of the NDK and ANDROID_HOME to the path of the SDK.

**Comment by JordiOfRivia** [comment]
> Hmm, are you sure that you have followed the [cargo-apk](https://github.com/tomaka/android-rs-glue#setting-up-your-environment) setup properly? Note at the end where it says
> 
> > * Set the environment variables NDK_HOME to the path of the NDK and ANDROID_HOME to the path of the SDK.

Hey ,
thanks for your answer i followed  the cargo-apk setup.
But how do i setup: Set the environment variables NDK_HOME to the path of the NDK and ANDROID_HOME to the path of the SDK.
On windows 10?

**Comment by OptimisticPeach** [comment]
Alright:
- Go to your control panel
- Look for "environment"
- Click on the option to "Edit the system environment variables":
![Capture](https://user-images.githubusercontent.com/24464956/54089266-9eee6380-433d-11e9-9116-bbd97b206d65.PNG)
- Click on the option to edit the environment variables as highlighted here:
![Capture](https://user-images.githubusercontent.com/24464956/54089280-cb09e480-433d-11e9-8cb4-9cdf5127a35c.PNG)
- Now, you may need to edit existing system environment variables or create a new one for them:
![image](https://user-images.githubusercontent.com/24464956/54089488-a57dda80-433f-11e9-9ec4-9f61953df0ff.png)
Either way, the dialog after that should be intuitive; just set the value of the new __User variables__ ___and___ the __System variables__ to be the locations of the install directories.

**Comment by JordiOfRivia** [comment]
Hey,
Thanks for the answer.
it is finally working.

**Comment by OptimisticPeach** [comment]
That's good to hear, although this is unmaintained so you will probably want to clone it locally to be able to make updates to the code, update dependencies etc. But beware with the hellscape that piston dependencies can be... It took me 3 days once to tell that two versions were difference. Also, changing a dependency to see what happens, getting a compiler error and running back to the previously working dependency doesn't always work. Sigh
